# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2630d1ff7e15e08addaa4049dcf353c50f5d41e8bd6a0b95a6cd1ef651700c87313bd41b8ffa86fc710f765a2b3b7f69001c77c5adf1439bb5891c42d957da7c

test:
  secret_key_base: 8fd905dd7d465b44403b33af0c7254e4db32a6c544ac64bd41e66482ce5a63f1cf2d7cec89d683cfb704b8c0e637cc220070a400cf9d75cd94bbb6ff6ee39f46

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
